### PR TITLE
Pull request for testing

### PR DESCRIPTION
**Pull request by rmzelle**

### CODE REVIEW

**Comment by rmzelle** [comment]
@inukshuk, nope, nothing. Can you look up the notification payload for this Travis CI test, or do you need to re-enable logging first?

**Comment by inukshuk** [comment]
I disabled the auth header verification (so that Sheldon accepts all notifications) and tried here at #8 -- same result, the issue/PR number is zero. This exact scenario was working previously.

**Comment by rmzelle** [comment]
Okay, thanks. Would be good to leave a note in the Travis issue tracker that this is reproducible across repos.

**Comment by rmzelle** [comment]
@inukshuk, per https://github.com/travis-ci/travis-ci/issues/4930#issuecomment-150202477 I added another commit to this PR, but we didn't get a Sheldon comment. Can you check the log?

**Comment by inukshuk** [comment]
Can you try on the official repo? (I re-enabled the auth header verification so it wouldn't work on my fork).

**Pull request closed without merging**
