### PR TITLE
Shelbot testing

### PR DESCRIPTION
**Pull request by inukshuk**

### CODE REVIEW

**Comment by rmzelle** [comment]
@inukshuk, is Sheldon still checking this repository? It might be interesting to create another pull request in this repo, since things worked here (just in case there is something funky going on with the official CSL styles repo).

**Comment by inukshuk** [comment]
I had a similar thought. I think the main difference between my testing here and with the official repository is that here, I made a PR from one branch of the repository to another; whereas in the more common case you fork the repository and then open the PR on the original one. We should try it out, if only to help track the issue at Travis CI (I still think it's an issue there, because the title of the PR comes through just fine and the PR number being `0` doesn't make much sense).

I'll try to run another test here later.

**Comment by rmzelle** [comment]
I recently created a branch within the CSL repo, though, and that one didn't work either: https://github.com/citation-style-language/styles/pull/1734

**Comment by inukshuk** [comment]
Good to know. We should try it out here anyway: if it doesn't work we can be pretty sure it is a regression error on Travis CI's part. If it does work we can maybe figure out what makes the official repo different.

**Pull request closed without merging**
